# Not using "cpp" because the default tools are so old!
language: generic

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

    # works on Precise and Trusty
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8

    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9

    # works on Trusty
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-7 # Only to get the latest libstd++
            - clang-7
      env:
        - CC=clang-7
        - CXX=clang++-7

    # works on Trusty
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-8 # Only to get the latest libstd++
            - clang-8
      env:
        - CC=clang-8
        - CXX=clang++-8

    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-9
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-9 # Only to get the latest libstd++
            - clang-9
      env:
        - CC=clang-9
        - CXX=clang++-9

    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-10
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-9 # Only to get the latest libstd++. Xenial doesn't have GCC 10 right now..
            - clang-10
      env:
        - CC=clang-10
        - CXX=clang++-10

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo $CC
  - echo $CXX

before_script:
  - cmake --system-information info.txt && cat info.txt
  - mkdir build
  - cd build
  - cmake ..

script:
  - VERBOSE=1 make -j2 && ctest --verbose
